apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: udp-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: udp-client 
    spec:
      containers:
      - name: udp-client
        image: xtoph/aks-udp-client
        imagePullPolicy: Always
        env:
        - name: SERVER_ADDRESS
          # Replace with ClusterIP/ServiceIP
          value: "52.173.29.131"
